server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: database_dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  kafka:
    bootstrap-servers: localhost:9091
# disabled auto componentscan for repositories(redis)
  data:
    redis:
      repositories:
        enabled: false

# properties for swagger2(v3.0.0)
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

schedule:
  timeout:
    day: 1

logging:
  level:
    root: INFO
    org.hibernate.SQL: off
    org.hibernate.type: off
#    com.springboot.springsecurity: debug
#    org.hibernate.SQL: debug
    # print query parameter operate jpa query
#    org.hibernate.type: trace