# application properties for test
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: "jdbc:oracle:thin:@localhost:1521/xe"
    username: "batchtest"
    password: "batchtest"
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      minimum-idle: 5
      max-lifetime: 2400000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: true

#p6spy jpa logging level
decorator:
  datasource:
    p6spy:
      enable-logging: true